version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: usethislink
      POSTGRES_PASSWORD: usethislink
      POSTGRES_DB: usethislink
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  gateway:
    build: ./services/gateway
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - LINK_SERVICE_URL=http://link:8081
      - ANALYTICS_SERVICE_URL=http://analytics:8082
      - USER_SERVICE_URL=http://user:8083
    depends_on:
      - link
      - analytics
      - user
    volumes:
      - ./static:/app/static
      - ./templates:/app/templates

  link:
    build: ./services/link
    environment:
      - PORT=8081
      - PGHOST=postgres
      - PGPORT=5432
      - PGUSER=usethislink
      - PGPASSWORD=usethislink
      - PGDATABASE=usethislink
      - PGSCHEMA=link
      - BASE_URL=http://localhost:8080
    depends_on:
      - postgres

  analytics:
    build: ./services/analytics
    environment:
      - PORT=8082
      - PGHOST=postgres
      - PGPORT=5432
      - PGUSER=usethislink
      - PGPASSWORD=usethislink
      - PGDATABASE=usethislink
      - PGSCHEMA=analytics
      - BASE_URL=http://localhost:8080
    depends_on:
      - postgres

  user:
    build: ./services/user
    environment:
      - PORT=8083
      - PGHOST=postgres
      - PGPORT=5432
      - PGUSER=usethislink
      - PGPASSWORD=usethislink
      - PGDATABASE=usethislink
      - PGSCHEMA=user
      - BASE_URL=http://localhost:8080
      - SMTP_HOST=smtp.example.com
      - SMTP_PORT=587
      - SMTP_USER=youruser@example.com
      - SMTP_PASS=yourpassword
    depends_on:
      - postgres

volumes:
  pgdata: 